<a href="https://colab.research.google.com/github/Syauqi366/SyauqiRabbani_MachineLearning/blob/main/praktikum10mandiri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LATIHAN 1

In [1]:
from google.colab import drive
drive.mount ('/content/gdrive')

Mounted at /content/gdrive


In [2]:
path = "/content/gdrive/MyDrive/Praktikum_ml/praktikum10/"

In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


df = pd.read_csv(path + "weather_classification_data.csv")

In [9]:
X = df[["Temperature", "Wind Speed"]]
y = df["Cloud Cover"]

le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

best_k = 1
best_acc = 0

for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    pred = knn.predict(X_test)
    acc = accuracy_score(y_test, pred)

    if acc > best_acc:
        best_acc = acc
        best_k = k

print("Nilai k terbaik =", best_k)
print("Akurasi terbaik =", best_acc)


Nilai k terbaik = 8
Akurasi terbaik = 0.5409090909090909


In [11]:
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X, y_encoded)

test_value = pd.DataFrame([[16, 3]], columns=X.columns)
prediction = le.inverse_transform(knn_best.predict(test_value))

print("Persepsi Marry (16°C, 3 km/h):", prediction[0])

Persepsi Marry (16°C, 3 km/h): overcast


# LATIHAN 2




In [19]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
data = {
    "NIM": ["TI001","TI002","TI003","TI004","TI005","TI006","TI007","TI008","TI009","TI010"],
    "Hasil_Sebenarnya": ["Lulus","Lulus","Lulus","Lulus","Lulus",
                         "Tidak Lulus","Tidak Lulus","Tidak Lulus","Tidak Lulus","Tidak Lulus"],
    "Hasil_Prediksi":   ["Lulus","Lulus","Lulus","Tidak Lulus","Tidak Lulus",
                         "Lulus","Tidak Lulus","Tidak Lulus","Tidak Lulus","Tidak Lulus"]
}

df2 = pd.DataFrame(data)

# Konversi label ke bentuk biner
# Lulus = 1, Tidak Lulus = 0
df2['Sebenarnya_bin'] = df2['Hasil_Sebenarnya'].map({"Lulus": 1, "Tidak Lulus": 0})
df2['Prediksi_bin']   = df2['Hasil_Prediksi'].map({"Lulus": 1, "Tidak Lulus": 0})


In [16]:
cm = confusion_matrix(df2['Sebenarnya_bin'], df2['Prediksi_bin'])

In [17]:
accuracy = accuracy_score(df2['Sebenarnya_bin'], df2['Prediksi_bin'])
precision = precision_score(df2['Sebenarnya_bin'], df2['Prediksi_bin'])
recall = recall_score(df2['Sebenarnya_bin'], df2['Prediksi_bin'])


In [18]:
print("=== DATASET ===")
print(df2[['NIM','Hasil_Sebenarnya','Hasil_Prediksi']])
print("\n=== CONFUSION MATRIX ===")
print(cm)
print("\n=== METRIC HASIL ===")
print(f"Accuracy : {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall   : {recall:.2f}")

=== DATASET ===
     NIM Hasil_Sebenarnya Hasil_Prediksi
0  TI001            Lulus          Lulus
1  TI002            Lulus          Lulus
2  TI003            Lulus          Lulus
3  TI004            Lulus    Tidak Lulus
4  TI005            Lulus    Tidak Lulus
5  TI006      Tidak Lulus          Lulus
6  TI007      Tidak Lulus    Tidak Lulus
7  TI008      Tidak Lulus    Tidak Lulus
8  TI009      Tidak Lulus    Tidak Lulus
9  TI010      Tidak Lulus    Tidak Lulus

=== CONFUSION MATRIX ===
[[4 1]
 [2 3]]

=== METRIC HASIL ===
Accuracy : 0.70
Precision: 0.75
Recall   : 0.60


# LATIHAN 3


In [21]:
# Copy dataframe
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler # Import StandardScaler

# Reload the original weather classification data as 'df' was overwritten
weather_df = pd.read_csv(path + "weather_classification_data.csv")
data = weather_df.copy()

# Label Encoding untuk kolom kategorikal
categorical_cols = ["Cloud Cover", "Season", "Location"]
encoder = LabelEncoder()

for col in categorical_cols:
    data[col] = encoder.fit_transform(data[col])

# Pisahkan fitur dan target
X = data.drop("Weather Type", axis=1)
y = data["Weather Type"]

# Encode target
y = LabelEncoder().fit_transform(y)

# Scaling fitur numerik
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled[:5]

array([[-0.29493119,  0.21240351, -0.04808565,  0.88762913,  0.99753949,
         0.13420291, -0.52010407,  0.98783148, -0.58223095, -0.1188932 ],
       [ 1.14303484,  1.35138482, -0.19283608,  0.54329086,  0.99753949,
         0.15060156,  0.77642368, -0.72923141,  1.34576796, -0.1188932 ],
       [ 0.62536707, -0.23328483, -0.40996172, -1.17840051, -1.96611598,
         0.34657889,  0.25781258, -0.72923141,  0.01099948,  1.14470601],
       [ 1.0855162 ,  0.70761278, -1.20608908,  0.88762913, -1.96611598,
         0.54900815,  0.77642368, -0.72923141, -1.323769  , -1.3824924 ],
       [ 0.45281115,  0.26192444,  1.03754256,  0.38677346,  0.00965433,
        -0.40749027, -0.77940962,  0.98783148, -0.87884617,  1.14470601]])

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)


In [24]:
import numpy as np

errors = []

for k in range(1, 21):
    knn_temp = KNeighborsClassifier(n_neighbors=k)
    knn_temp.fit(X_train, y_train)
    pred_k = knn_temp.predict(X_test)
    errors.append(np.mean(pred_k != y_test))

best_k = np.argmin(errors) + 1
best_k

np.int64(8)

In [25]:
knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=np.int64(8))

In [27]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = knn.predict(X_test)

print("Akurasi:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Akurasi: 0.8965909090909091

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.89      0.86       651
           1       0.88      0.88      0.88       647
           2       0.94      0.94      0.94       701
           3       0.93      0.88      0.91       641

    accuracy                           0.90      2640
   macro avg       0.90      0.90      0.90      2640
weighted avg       0.90      0.90      0.90      2640


Confusion Matrix:
[[577  47  12  15]
 [ 45 567  22  13]
 [ 16  13 659  13]
 [ 47  19  11 564]]


In [30]:
# Contoh data baru (isi sesuai kebutuhan)
sample = pd.DataFrame({
    "Temperature": [28],
    "Humidity": [70],
    "Wind Speed": [5],
    "Precipitation (%)": [20],
    "Cloud Cover": ["clear"],
    "Atmospheric Pressure": [1010],
    "UV Index": [6],
    "Season": ["Summer"],
    "Visibility (km)": [8],
    "Location": ["inland"]
})

# Encode kategorikal
# Re-create and fit LabelEncoder for each categorical column for the sample
# The 'categorical_cols' and 'weather_df' are available from previous cells.
for col in categorical_cols:
    # Concatenate unique categories from original data and the new sample
    all_categories = pd.concat([weather_df[col], sample[col]], axis=0).unique()

    temp_encoder = LabelEncoder()
    temp_encoder.fit(all_categories)
    sample[col] = temp_encoder.transform(sample[col])

# Scaling
sample_scaled = scaler.transform(sample)

# Prediksi
pred_encoded = knn.predict(sample_scaled)[0]

# To inverse transform the prediction, we need the LabelEncoder used for the target variable 'Weather Type'.
# This encoder was not globally stored in previous cells, so we re-create it here.
target_le = LabelEncoder()
target_le.fit(weather_df["Weather Type"]) # Fit on all original Weather Type categories
prediction = target_le.inverse_transform([pred_encoded])[0]

print("Prediksi Weather Type untuk data baru:", prediction)


Prediksi Weather Type untuk data baru: Sunny
